#!/usr/bin/python3
import sys
import subprocess

if __name__ == "__main__":
    if len(sys.argv) == 2:
        map = sys.argv[1]
        subprocess.run("osascript -e 'tell application \"Terminal\" to do script \"~/.aiosaber/client/aiosaber-client --map-install " + map + "\"'", shell=True)
    else:
        print("Error: no url provided")
